# Data Cleaning

In [41]:
# lets import our data
from load_data import *
df = load_unprocessed_data()

In [16]:
def drop_nulls(df, subset=None):
    """
    Drop rows with null values from the DataFrame.
    
    Parameters:
    df (pl.DataFrame): The DataFrame to clean.
    subset (list of str, optional): Columns to consider for null values. If None, considers all columns.
    
    Returns:
    pl.DataFrame: DataFrame with null rows dropped.
    """
    return df.drop_nulls(subset=subset)

## Handling missing data

In [2]:
df

shape: (1_200, 13)
┌─────┬────────┬─────────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ age ┆ gender ┆ daily_socia ┆ platform_us ┆ … ┆ stress_lev ┆ anxiety_le ┆ addiction_ ┆ depression │
│ --- ┆ ---    ┆ l_media_hou ┆ age         ┆   ┆ el         ┆ vel        ┆ level      ┆ _label     │
│ i64 ┆ str    ┆ rs          ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│     ┆        ┆ ---         ┆ str         ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
│     ┆        ┆ f64         ┆             ┆   ┆            ┆            ┆            ┆            │
╞═════╪════════╪═════════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 14  ┆ male   ┆ 7.9         ┆ Instagram   ┆ … ┆ 2          ┆ 2          ┆ 1          ┆ 0          │
│ 19  ┆ female ┆ 1.9         ┆ TikTok      ┆ … ┆ 8          ┆ 1          ┆ 10         ┆ 0          │
│ 17  ┆ female ┆ 1.3         ┆ Instagram   ┆ … ┆ 2          ┆ 4          ┆ 2          ┆ 0          │
│ 15  ┆ male   ┆ 7.4         ┆ TikTok      ┆ … ┆ 1          ┆ 7          ┆ 9          ┆ 0          │
│ 15  ┆ female ┆ 4.7         ┆ Both        ┆ … ┆ 3          ┆ 5          ┆ 2          ┆ 0          │
│ …   ┆ …      ┆ …           ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 18  ┆ female ┆ 6.8         ┆ Instagram   ┆ … ┆ 3          ┆ 4          ┆ 4          ┆ 0          │
│ 16  ┆ male   ┆ 2.3         ┆ Both        ┆ … ┆ 7          ┆ 4          ┆ 4          ┆ 0          │
│ 14  ┆ female ┆ 1.7         ┆ Both        ┆ … ┆ 1          ┆ 1          ┆ 1          ┆ 0          │
│ 15  ┆ male   ┆ 3.9         ┆ Both        ┆ … ┆ 7          ┆ 9          ┆ 9          ┆ 0          │
│ 16  ┆ female ┆ 4.7         ┆ TikTok      ┆ … ┆ 5          ┆ 7          ┆ 3          ┆ 0          │
└─────┴────────┴─────────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [42]:
df.shape

(1200, 13)

In [11]:
df.unique()

shape: (1_200, 13)
┌─────┬────────┬─────────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ age ┆ gender ┆ daily_socia ┆ platform_us ┆ … ┆ stress_lev ┆ anxiety_le ┆ addiction_ ┆ depression │
│ --- ┆ ---    ┆ l_media_hou ┆ age         ┆   ┆ el         ┆ vel        ┆ level      ┆ _label     │
│ i64 ┆ str    ┆ rs          ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│     ┆        ┆ ---         ┆ str         ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
│     ┆        ┆ f64         ┆             ┆   ┆            ┆            ┆            ┆            │
╞═════╪════════╪═════════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 19  ┆ female ┆ 7.9         ┆ TikTok      ┆ … ┆ 6          ┆ 1          ┆ 8          ┆ 0          │
│ 14  ┆ male   ┆ 4.2         ┆ Both        ┆ … ┆ 4          ┆ 8          ┆ 1          ┆ 0          │
│ 19  ┆ male   ┆ 7.2         ┆ Instagram   ┆ … ┆ 6          ┆ 9          ┆ 2          ┆ 0          │
│ 15  ┆ female ┆ 1.1         ┆ TikTok      ┆ … ┆ 10         ┆ 7          ┆ 9          ┆ 0          │
│ 13  ┆ female ┆ 1.3         ┆ TikTok      ┆ … ┆ 10         ┆ 9          ┆ 9          ┆ 0          │
│ …   ┆ …      ┆ …           ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 19  ┆ male   ┆ 2.7         ┆ Both        ┆ … ┆ 10         ┆ 8          ┆ 7          ┆ 0          │
│ 15  ┆ female ┆ 2.2         ┆ Instagram   ┆ … ┆ 6          ┆ 1          ┆ 7          ┆ 0          │
│ 15  ┆ male   ┆ 3.7         ┆ Both        ┆ … ┆ 4          ┆ 9          ┆ 10         ┆ 0          │
│ 18  ┆ female ┆ 7.1         ┆ Instagram   ┆ … ┆ 3          ┆ 1          ┆ 6          ┆ 0          │
│ 14  ┆ male   ┆ 5.0         ┆ Both        ┆ … ┆ 9          ┆ 4          ┆ 10         ┆ 0          │
└─────┴────────┴─────────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [17]:
df = drop_nulls(df)
df

shape: (1_200, 13)
┌─────┬────────┬─────────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ age ┆ gender ┆ daily_socia ┆ platform_us ┆ … ┆ stress_lev ┆ anxiety_le ┆ addiction_ ┆ depression │
│ --- ┆ ---    ┆ l_media_hou ┆ age         ┆   ┆ el         ┆ vel        ┆ level      ┆ _label     │
│ i64 ┆ str    ┆ rs          ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│     ┆        ┆ ---         ┆ str         ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
│     ┆        ┆ f64         ┆             ┆   ┆            ┆            ┆            ┆            │
╞═════╪════════╪═════════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 14  ┆ male   ┆ 7.9         ┆ Instagram   ┆ … ┆ 2          ┆ 2          ┆ 1          ┆ 0          │
│ 19  ┆ female ┆ 1.9         ┆ TikTok      ┆ … ┆ 8          ┆ 1          ┆ 10         ┆ 0          │
│ 17  ┆ female ┆ 1.3         ┆ Instagram   ┆ … ┆ 2          ┆ 4          ┆ 2          ┆ 0          │
│ 15  ┆ male   ┆ 7.4         ┆ TikTok      ┆ … ┆ 1          ┆ 7          ┆ 9          ┆ 0          │
│ 15  ┆ female ┆ 4.7         ┆ Both        ┆ … ┆ 3          ┆ 5          ┆ 2          ┆ 0          │
│ …   ┆ …      ┆ …           ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 18  ┆ female ┆ 6.8         ┆ Instagram   ┆ … ┆ 3          ┆ 4          ┆ 4          ┆ 0          │
│ 16  ┆ male   ┆ 2.3         ┆ Both        ┆ … ┆ 7          ┆ 4          ┆ 4          ┆ 0          │
│ 14  ┆ female ┆ 1.7         ┆ Both        ┆ … ┆ 1          ┆ 1          ┆ 1          ┆ 0          │
│ 15  ┆ male   ┆ 3.9         ┆ Both        ┆ … ┆ 7          ┆ 9          ┆ 9          ┆ 0          │
│ 16  ┆ female ┆ 4.7         ┆ TikTok      ┆ … ┆ 5          ┆ 7          ┆ 3          ┆ 0          │
└─────┴────────┴─────────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [43]:
def clean_and_report_changes(df):
    """
    Drops null values and duplicates from the DataFrame, and reports row changes at each step.
    Returns the cleaned DataFrame and a dict with row counts.
    """
    initial_rows = df.shape[0]
    df_no_nulls = df.drop_nulls()
    after_nulls = df_no_nulls.shape[0]
    df_no_dupes = df_no_nulls.unique()
    after_dupes = df_no_dupes.shape[0]
    changes = {
        'initial_rows': initial_rows,
        'after_drop_nulls': after_nulls,
        'after_drop_duplicates': after_dupes,
        'nulls_dropped': initial_rows - after_nulls,
        'duplicates_dropped': after_nulls - after_dupes
    }
    return df_no_dupes, changes

# Example usage:
# cleaned_df, row_changes = clean_and_report_changes(df)
# print(row_changes)

In [44]:
cleaned_df, row_changes = clean_and_report_changes(df)

In [45]:
cleaned_df

shape: (1_200, 13)
┌─────┬────────┬─────────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ age ┆ gender ┆ daily_socia ┆ platform_us ┆ … ┆ stress_lev ┆ anxiety_le ┆ addiction_ ┆ depression │
│ --- ┆ ---    ┆ l_media_hou ┆ age         ┆   ┆ el         ┆ vel        ┆ level      ┆ _label     │
│ i64 ┆ str    ┆ rs          ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│     ┆        ┆ ---         ┆ str         ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
│     ┆        ┆ f64         ┆             ┆   ┆            ┆            ┆            ┆            │
╞═════╪════════╪═════════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 18  ┆ male   ┆ 6.7         ┆ Instagram   ┆ … ┆ 5          ┆ 8          ┆ 3          ┆ 0          │
│ 17  ┆ female ┆ 2.3         ┆ Instagram   ┆ … ┆ 3          ┆ 7          ┆ 7          ┆ 0          │
│ 15  ┆ male   ┆ 3.2         ┆ Instagram   ┆ … ┆ 6          ┆ 3          ┆ 1          ┆ 0          │
│ 14  ┆ male   ┆ 3.4         ┆ Instagram   ┆ … ┆ 7          ┆ 10         ┆ 6          ┆ 0          │
│ 17  ┆ female ┆ 1.3         ┆ Instagram   ┆ … ┆ 2          ┆ 4          ┆ 2          ┆ 0          │
│ …   ┆ …      ┆ …           ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 15  ┆ female ┆ 4.2         ┆ TikTok      ┆ … ┆ 6          ┆ 6          ┆ 4          ┆ 0          │
│ 17  ┆ male   ┆ 3.5         ┆ Instagram   ┆ … ┆ 4          ┆ 5          ┆ 9          ┆ 0          │
│ 19  ┆ female ┆ 4.1         ┆ Instagram   ┆ … ┆ 7          ┆ 3          ┆ 4          ┆ 0          │
│ 15  ┆ female ┆ 4.2         ┆ Both        ┆ … ┆ 4          ┆ 1          ┆ 3          ┆ 0          │
│ 15  ┆ male   ┆ 3.8         ┆ TikTok      ┆ … ┆ 2          ┆ 9          ┆ 7          ┆ 0          │
└─────┴────────┴─────────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [46]:
row_changes

{'initial_rows': 1200,
 'after_drop_nulls': 1200,
 'after_drop_duplicates': 1200,
 'nulls_dropped': 0,
 'duplicates_dropped': 0}

## Removing Outliers

In [47]:
import polars as pl

def remove_outliers_iqr(data: pl.DataFrame) -> pl.DataFrame:
    """
    Removes rows containing outliers in any numeric column using the IQR method.
    Returns a DataFrame with outliers removed.
    """
    numeric_cols = [col for col, dtype in zip(data.columns, data.dtypes)
                    if dtype in (pl.Int64, pl.Int32, pl.Float64, pl.Float32)]
    mask = None
    for col in numeric_cols:
        q1 = data.select(pl.col(col).quantile(0.25)).item()
        q3 = data.select(pl.col(col).quantile(0.75)).item()
        iqr = q3 - q1
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr
        col_mask = (data[col] >= lower_bound) & (data[col] <= upper_bound)
        mask = col_mask if mask is None else (mask & col_mask)
    cleaned = data.filter(mask) if mask is not None else data
    return cleaned

# Example usage:
# df = remove_outliers_iqr(df)

In [48]:
df = remove_outliers_iqr(cleaned_df)

## Checking the dataframes shape

In [49]:
df.shape

(1169, 13)

## Now making our final EDA report after cleaning process

In [50]:
import sweetviz as sv
report = sv.analyze(df.to_pandas())
report.show_html("../reports/Clean-EDA-Report.html")

                                             |          | [  0%]   00:00 -> (? left)

Report ../reports/Clean-EDA-Report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

## Final Data Description

In [51]:
df.describe()

shape: (9, 14)
┌────────────┬───────────┬────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ age       ┆ gender ┆ daily_soci ┆ … ┆ stress_le ┆ anxiety_l ┆ addiction ┆ depressio │
│ ---        ┆ ---       ┆ ---    ┆ al_media_h ┆   ┆ vel       ┆ evel      ┆ _level    ┆ n_label   │
│ str        ┆ f64       ┆ str    ┆ ours       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆           ┆        ┆ ---        ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
│            ┆           ┆        ┆ f64        ┆   ┆           ┆           ┆           ┆           │
╞════════════╪═══════════╪════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 1169.0    ┆ 1169   ┆ 1169.0     ┆ … ┆ 1169.0    ┆ 1169.0    ┆ 1169.0    ┆ 1169.0    │
│ null_count ┆ 0.0       ┆ 0      ┆ 0.0        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 15.924722 ┆ null   ┆ 4.478785   ┆ … ┆ 5.365269  ┆ 5.557742  ┆ 5.571429  ┆ 0.0       │
│ std        ┆ 2.021582  ┆ null   ┆ 2.018025   ┆ … ┆ 2.89204   ┆ 2.850191  ┆ 2.826351  ┆ 0.0       │
│ min        ┆ 13.0      ┆ female ┆ 1.0        ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 0.0       │
│ 25%        ┆ 14.0      ┆ null   ┆ 2.7        ┆ … ┆ 3.0       ┆ 3.0       ┆ 3.0       ┆ 0.0       │
│ 50%        ┆ 16.0      ┆ null   ┆ 4.4        ┆ … ┆ 5.0       ┆ 6.0       ┆ 6.0       ┆ 0.0       │
│ 75%        ┆ 18.0      ┆ null   ┆ 6.2        ┆ … ┆ 8.0       ┆ 8.0       ┆ 8.0       ┆ 0.0       │
│ max        ┆ 19.0      ┆ male   ┆ 8.0        ┆ … ┆ 10.0      ┆ 10.0      ┆ 10.0      ┆ 0.0       │
└────────────┴───────────┴────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Final Findings of the Data
- We have 8 catergorical columns
- 5 Numerical columns

## Lets save our processed data

In [53]:
from save_cleaned_data import save_cleaned_data
save_cleaned_data(df)
df.shape

(1169, 13)