# Data Cleaning

In [1]:
# lets import our data
from load_data import load_unprocessed_data
df = load_unprocessed_data()

In [16]:
def drop_nulls(df, subset=None):
    """
    Drop rows with null values from the DataFrame.
    
    Parameters:
    df (pl.DataFrame): The DataFrame to clean.
    subset (list of str, optional): Columns to consider for null values. If None, considers all columns.
    
    Returns:
    pl.DataFrame: DataFrame with null rows dropped.
    """
    return df.drop_nulls(subset=subset)

## Handling missing data

In [2]:
df

shape: (1_200, 13)
┌─────┬────────┬─────────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ age ┆ gender ┆ daily_socia ┆ platform_us ┆ … ┆ stress_lev ┆ anxiety_le ┆ addiction_ ┆ depression │
│ --- ┆ ---    ┆ l_media_hou ┆ age         ┆   ┆ el         ┆ vel        ┆ level      ┆ _label     │
│ i64 ┆ str    ┆ rs          ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│     ┆        ┆ ---         ┆ str         ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
│     ┆        ┆ f64         ┆             ┆   ┆            ┆            ┆            ┆            │
╞═════╪════════╪═════════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 14  ┆ male   ┆ 7.9         ┆ Instagram   ┆ … ┆ 2          ┆ 2          ┆ 1          ┆ 0          │
│ 19  ┆ female ┆ 1.9         ┆ TikTok      ┆ … ┆ 8          ┆ 1          ┆ 10         ┆ 0          │
│ 17  ┆ female ┆ 1.3         ┆ Instagram   ┆ … ┆ 2          ┆ 4          ┆ 2          ┆ 0          │
│ 15  ┆ male   ┆ 7.4         ┆ TikTok      ┆ … ┆ 1          ┆ 7          ┆ 9          ┆ 0          │
│ 15  ┆ female ┆ 4.7         ┆ Both        ┆ … ┆ 3          ┆ 5          ┆ 2          ┆ 0          │
│ …   ┆ …      ┆ …           ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 18  ┆ female ┆ 6.8         ┆ Instagram   ┆ … ┆ 3          ┆ 4          ┆ 4          ┆ 0          │
│ 16  ┆ male   ┆ 2.3         ┆ Both        ┆ … ┆ 7          ┆ 4          ┆ 4          ┆ 0          │
│ 14  ┆ female ┆ 1.7         ┆ Both        ┆ … ┆ 1          ┆ 1          ┆ 1          ┆ 0          │
│ 15  ┆ male   ┆ 3.9         ┆ Both        ┆ … ┆ 7          ┆ 9          ┆ 9          ┆ 0          │
│ 16  ┆ female ┆ 4.7         ┆ TikTok      ┆ … ┆ 5          ┆ 7          ┆ 3          ┆ 0          │
└─────┴────────┴─────────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [7]:
df.shape

(1200, 13)

In [11]:
df.unique()

shape: (1_200, 13)
┌─────┬────────┬─────────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ age ┆ gender ┆ daily_socia ┆ platform_us ┆ … ┆ stress_lev ┆ anxiety_le ┆ addiction_ ┆ depression │
│ --- ┆ ---    ┆ l_media_hou ┆ age         ┆   ┆ el         ┆ vel        ┆ level      ┆ _label     │
│ i64 ┆ str    ┆ rs          ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│     ┆        ┆ ---         ┆ str         ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
│     ┆        ┆ f64         ┆             ┆   ┆            ┆            ┆            ┆            │
╞═════╪════════╪═════════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 19  ┆ female ┆ 7.9         ┆ TikTok      ┆ … ┆ 6          ┆ 1          ┆ 8          ┆ 0          │
│ 14  ┆ male   ┆ 4.2         ┆ Both        ┆ … ┆ 4          ┆ 8          ┆ 1          ┆ 0          │
│ 19  ┆ male   ┆ 7.2         ┆ Instagram   ┆ … ┆ 6          ┆ 9          ┆ 2          ┆ 0          │
│ 15  ┆ female ┆ 1.1         ┆ TikTok      ┆ … ┆ 10         ┆ 7          ┆ 9          ┆ 0          │
│ 13  ┆ female ┆ 1.3         ┆ TikTok      ┆ … ┆ 10         ┆ 9          ┆ 9          ┆ 0          │
│ …   ┆ …      ┆ …           ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 19  ┆ male   ┆ 2.7         ┆ Both        ┆ … ┆ 10         ┆ 8          ┆ 7          ┆ 0          │
│ 15  ┆ female ┆ 2.2         ┆ Instagram   ┆ … ┆ 6          ┆ 1          ┆ 7          ┆ 0          │
│ 15  ┆ male   ┆ 3.7         ┆ Both        ┆ … ┆ 4          ┆ 9          ┆ 10         ┆ 0          │
│ 18  ┆ female ┆ 7.1         ┆ Instagram   ┆ … ┆ 3          ┆ 1          ┆ 6          ┆ 0          │
│ 14  ┆ male   ┆ 5.0         ┆ Both        ┆ … ┆ 9          ┆ 4          ┆ 10         ┆ 0          │
└─────┴────────┴─────────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [17]:
df = drop_nulls(df)
df

shape: (1_200, 13)
┌─────┬────────┬─────────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ age ┆ gender ┆ daily_socia ┆ platform_us ┆ … ┆ stress_lev ┆ anxiety_le ┆ addiction_ ┆ depression │
│ --- ┆ ---    ┆ l_media_hou ┆ age         ┆   ┆ el         ┆ vel        ┆ level      ┆ _label     │
│ i64 ┆ str    ┆ rs          ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│     ┆        ┆ ---         ┆ str         ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
│     ┆        ┆ f64         ┆             ┆   ┆            ┆            ┆            ┆            │
╞═════╪════════╪═════════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 14  ┆ male   ┆ 7.9         ┆ Instagram   ┆ … ┆ 2          ┆ 2          ┆ 1          ┆ 0          │
│ 19  ┆ female ┆ 1.9         ┆ TikTok      ┆ … ┆ 8          ┆ 1          ┆ 10         ┆ 0          │
│ 17  ┆ female ┆ 1.3         ┆ Instagram   ┆ … ┆ 2          ┆ 4          ┆ 2          ┆ 0          │
│ 15  ┆ male   ┆ 7.4         ┆ TikTok      ┆ … ┆ 1          ┆ 7          ┆ 9          ┆ 0          │
│ 15  ┆ female ┆ 4.7         ┆ Both        ┆ … ┆ 3          ┆ 5          ┆ 2          ┆ 0          │
│ …   ┆ …      ┆ …           ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 18  ┆ female ┆ 6.8         ┆ Instagram   ┆ … ┆ 3          ┆ 4          ┆ 4          ┆ 0          │
│ 16  ┆ male   ┆ 2.3         ┆ Both        ┆ … ┆ 7          ┆ 4          ┆ 4          ┆ 0          │
│ 14  ┆ female ┆ 1.7         ┆ Both        ┆ … ┆ 1          ┆ 1          ┆ 1          ┆ 0          │
│ 15  ┆ male   ┆ 3.9         ┆ Both        ┆ … ┆ 7          ┆ 9          ┆ 9          ┆ 0          │
│ 16  ┆ female ┆ 4.7         ┆ TikTok      ┆ … ┆ 5          ┆ 7          ┆ 3          ┆ 0          │
└─────┴────────┴─────────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘