# Data Profile
- Conducting generic statistics on the data
- Checking for 
    - Missing Values
    - Duplicates
    - Data type consistency
    - Outliers

In [2]:
# load_unprocessed data - is a function from the load_data.py file which loads data from ../data/raw folder
from load_data import load_unprocessed_data
from ydata_profiling import ProfileReport
import polars as pl

Matplotlib is building the font cache; this may take a moment.

## Loading our data from the parquet file
- data\raw\unprocessed_data.parquet

In [72]:
df = load_unprocessed_data()

# Now we look at our data

In [73]:
#Viewing the top 5 rows
df.head(5)

shape: (5, 13)
┌─────┬────────┬─────────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ age ┆ gender ┆ daily_socia ┆ platform_us ┆ … ┆ stress_lev ┆ anxiety_le ┆ addiction_ ┆ depression │
│ --- ┆ ---    ┆ l_media_hou ┆ age         ┆   ┆ el         ┆ vel        ┆ level      ┆ _label     │
│ i64 ┆ str    ┆ rs          ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│     ┆        ┆ ---         ┆ str         ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
│     ┆        ┆ f64         ┆             ┆   ┆            ┆            ┆            ┆            │
╞═════╪════════╪═════════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 14  ┆ male   ┆ 7.9         ┆ Instagram   ┆ … ┆ 2          ┆ 2          ┆ 1          ┆ 0          │
│ 19  ┆ female ┆ 1.9         ┆ TikTok      ┆ … ┆ 8          ┆ 1          ┆ 10         ┆ 0          │
│ 17  ┆ female ┆ 1.3         ┆ Instagram   ┆ … ┆ 2          ┆ 4          ┆ 2          ┆ 0          │
│ 15  ┆ male   ┆ 7.4         ┆ TikTok      ┆ … ┆ 1          ┆ 7          ┆ 9          ┆ 0          │
│ 15  ┆ female ┆ 4.7         ┆ Both        ┆ … ┆ 3          ┆ 5          ┆ 2          ┆ 0          │
└─────┴────────┴─────────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [74]:
#Viewing the last 5 rows
df.tail(5)

shape: (5, 13)
┌─────┬────────┬─────────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ age ┆ gender ┆ daily_socia ┆ platform_us ┆ … ┆ stress_lev ┆ anxiety_le ┆ addiction_ ┆ depression │
│ --- ┆ ---    ┆ l_media_hou ┆ age         ┆   ┆ el         ┆ vel        ┆ level      ┆ _label     │
│ i64 ┆ str    ┆ rs          ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│     ┆        ┆ ---         ┆ str         ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
│     ┆        ┆ f64         ┆             ┆   ┆            ┆            ┆            ┆            │
╞═════╪════════╪═════════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 18  ┆ female ┆ 6.8         ┆ Instagram   ┆ … ┆ 3          ┆ 4          ┆ 4          ┆ 0          │
│ 16  ┆ male   ┆ 2.3         ┆ Both        ┆ … ┆ 7          ┆ 4          ┆ 4          ┆ 0          │
│ 14  ┆ female ┆ 1.7         ┆ Both        ┆ … ┆ 1          ┆ 1          ┆ 1          ┆ 0          │
│ 15  ┆ male   ┆ 3.9         ┆ Both        ┆ … ┆ 7          ┆ 9          ┆ 9          ┆ 0          │
│ 16  ┆ female ┆ 4.7         ┆ TikTok      ┆ … ┆ 5          ┆ 7          ┆ 3          ┆ 0          │
└─────┴────────┴─────────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [75]:
#Viewing the shape of our data
# In this case, we have 1200 rows and 13 columns
shape = df.shape
print(f"The shape of our data is: {shape}")
print(f"The number of rows is: {shape[0]}")
print(f"The number of columns is: {shape[1]}")

The shape of our data is: (1200, 13)
The number of rows is: 1200
The number of columns is: 13

## Descriptive analytics
- Mean
- Mode
- Median
- Standard Deviation

In [76]:
#Viewing the summary statistics of our data
df.describe()

shape: (9, 14)
┌────────────┬───────────┬────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ age       ┆ gender ┆ daily_soci ┆ … ┆ stress_le ┆ anxiety_l ┆ addiction ┆ depressio │
│ ---        ┆ ---       ┆ ---    ┆ al_media_h ┆   ┆ vel       ┆ evel      ┆ _level    ┆ n_label   │
│ str        ┆ f64       ┆ str    ┆ ours       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆           ┆        ┆ ---        ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
│            ┆           ┆        ┆ f64        ┆   ┆           ┆           ┆           ┆           │
╞════════════╪═══════════╪════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 1200.0    ┆ 1200   ┆ 1200.0     ┆ … ┆ 1200.0    ┆ 1200.0    ┆ 1200.0    ┆ 1200.0    │
│ null_count ┆ 0.0       ┆ 0      ┆ 0.0        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 15.928333 ┆ null   ┆ 4.536667   ┆ … ┆ 5.445833  ┆ 5.636667  ┆ 5.565     ┆ 0.025833  │
│ std        ┆ 2.021947  ┆ null   ┆ 2.029599   ┆ … ┆ 2.90329   ┆ 2.859453  ┆ 2.830627  ┆ 0.158704  │
│ min        ┆ 13.0      ┆ female ┆ 1.0        ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 0.0       │
│ 25%        ┆ 14.0      ┆ null   ┆ 2.8        ┆ … ┆ 3.0       ┆ 3.0       ┆ 3.0       ┆ 0.0       │
│ 50%        ┆ 16.0      ┆ null   ┆ 4.5        ┆ … ┆ 5.0       ┆ 6.0       ┆ 6.0       ┆ 0.0       │
│ 75%        ┆ 18.0      ┆ null   ┆ 6.3        ┆ … ┆ 8.0       ┆ 8.0       ┆ 8.0       ┆ 0.0       │
│ max        ┆ 19.0      ┆ male   ┆ 8.0        ┆ … ┆ 10.0      ┆ 10.0      ┆ 10.0      ┆ 1.0       │
└────────────┴───────────┴────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Now we check for missing values

In [77]:
# Checking for the total of null values in each column
nulls = df.select(pl.all().is_null()).sum()
nulls_dict = nulls.to_dict(as_series=False)
print("Number of null values in each column:")
for column, null_count in nulls_dict.items():
    print(f"{column}: {null_count}")

Number of null values in each column:
age: [0]
gender: [0]
daily_social_media_hours: [0]
platform_usage: [0]
sleep_hours: [0]
screen_time_before_sleep: [0]
academic_performance: [0]
physical_activity: [0]
social_interaction_level: [0]
stress_level: [0]
anxiety_level: [0]
addiction_level: [0]
depression_label: [0]

## Now we check for duplicates

In [78]:
duplicates = df.is_duplicated().sum()
print(f"Number of duplicated rows: {duplicates}")

Number of duplicated rows: 0

In [79]:
duplicates = df.select(pl.all().is_duplicated()).sum()
duplicates_dict = duplicates.to_dict(as_series=False)
duplicates_count = duplicates_dict.get("is_duplicated", 0)
print(f"Number of duplicated rows: {duplicates_count}")

Number of duplicated rows: 0

# Checking data types

In [80]:
data_types = df.schema
print("Data types of each column:")     
for column, dtype in data_types.items():
    print(f"{column}: {dtype}")

Data types of each column:
age: Int64
gender: String
daily_social_media_hours: Float64
platform_usage: String
sleep_hours: Float64
screen_time_before_sleep: Float64
academic_performance: Float64
physical_activity: Float64
social_interaction_level: String
stress_level: Int64
anxiety_level: Int64
addiction_level: Int64
depression_label: Int64

## Checking for Outliers in our Data

In [81]:
def detect_outliers_iqr(data: pl.DataFrame) -> pl.DataFrame:
    numeric_cols = [col for col, dtype in zip(data.columns, data.dtypes) 
                    if dtype in (pl.Int64, pl.Int32, pl.Float64, pl.Float32)]
    
    outlier_flags = []
    
    for col in numeric_cols:
        q1 = data.select(pl.col(col).quantile(0.25)).item()
        q3 = data.select(pl.col(col).quantile(0.75)).item()
        iqr = q3 - q1
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr
        
        # Boolean mask for outliers in this column
        mask = (pl.col(col) < lower_bound) | (pl.col(col) > upper_bound)
        outlier_flags.append(mask.alias(f"{col}_is_outlier"))
    
    # Combine original data with outlier flags
    outlier_df = data.with_columns(outlier_flags)
    
    # Count and print the number of outliers for each numeric column
    for col in numeric_cols:
        outlier_col = f"{col}_is_outlier"
        count = outlier_df.select(pl.col(outlier_col).sum()).item()
        print(f"Number of outliers in {col}: {count}")
    
    return outlier_df

In [1]:
detect_outliers_iqr(df)

NameError: name 'detect_outliers_iqr' is not defined

In [67]:
df

shape: (1_200, 13)
┌─────┬────────┬─────────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ age ┆ gender ┆ daily_socia ┆ platform_us ┆ … ┆ stress_lev ┆ anxiety_le ┆ addiction_ ┆ depression │
│ --- ┆ ---    ┆ l_media_hou ┆ age         ┆   ┆ el         ┆ vel        ┆ level      ┆ _label     │
│ i64 ┆ str    ┆ rs          ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│     ┆        ┆ ---         ┆ str         ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
│     ┆        ┆ f64         ┆             ┆   ┆            ┆            ┆            ┆            │
╞═════╪════════╪═════════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 14  ┆ male   ┆ 7.9         ┆ Instagram   ┆ … ┆ 2          ┆ 2          ┆ 1          ┆ 0          │
│ 19  ┆ female ┆ 1.9         ┆ TikTok      ┆ … ┆ 8          ┆ 1          ┆ 10         ┆ 0          │
│ 17  ┆ female ┆ 1.3         ┆ Instagram   ┆ … ┆ 2          ┆ 4          ┆ 2          ┆ 0          │
│ 15  ┆ male   ┆ 7.4         ┆ TikTok      ┆ … ┆ 1          ┆ 7          ┆ 9          ┆ 0          │
│ 15  ┆ female ┆ 4.7         ┆ Both        ┆ … ┆ 3          ┆ 5          ┆ 2          ┆ 0          │
│ …   ┆ …      ┆ …           ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 18  ┆ female ┆ 6.8         ┆ Instagram   ┆ … ┆ 3          ┆ 4          ┆ 4          ┆ 0          │
│ 16  ┆ male   ┆ 2.3         ┆ Both        ┆ … ┆ 7          ┆ 4          ┆ 4          ┆ 0          │
│ 14  ┆ female ┆ 1.7         ┆ Both        ┆ … ┆ 1          ┆ 1          ┆ 1          ┆ 0          │
│ 15  ┆ male   ┆ 3.9         ┆ Both        ┆ … ┆ 7          ┆ 9          ┆ 9          ┆ 0          │
│ 16  ┆ female ┆ 4.7         ┆ TikTok      ┆ … ┆ 5          ┆ 7          ┆ 3          ┆ 0          │
└─────┴────────┴─────────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

# Creating an EDA Report 
- Using sweetviz

In [96]:
import sweetviz as sv
report = sv.analyze(df.to_pandas())
report.show_html("../reports/EDAReport.html")

Done! Use 'show' commands to display/save.   |██████████| [100%]   00:05 -> (00:00 left)

Report ../reports/EDAReport.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.